### PR TITLE
studentgoals

### PR DESCRIPTION
**Pull request by michelleewu**
Here are two goals that I hope to achieve throughout the school year with my partner, Jessica Song

### CODE REVIEW

**Comment by twang** [comment]
Don't forget the second rubric!

**Comment by 7essica** [comment]
I really like your goals for this school year! One thing you can do to make your goals better is making the goals more measurable, for example, for your first goal you can say, "I want to get a 5 on the AP test." thus you can see if you've reached your goal or not clearly, but other than that it's all perfect.

**Comment by michelleewu** [comment]
Note to self see https://github.com/twangcs/student-goals-michelleewu/blob/master/rubric2.txt

**Comment by twang** [comment]
Nice, thanks!

**Pull request merged**
